using System;
using System.Net.Sockets;
using System.Net.WebSockets;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using wiFind.Server;

namespace wiFind.Server.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SupportTicketController : ControllerBase
    {
        private readonly WiFindContext server;

        public SupportTicketController(WiFindContext s)
        {
            server = s;
        }

        [HttpPost]
        public async Task<IActionResult> SubmitTicket(SupportTicket ticket)
        {
            if (!ModelState.IsValid) return BadRequest("Invalid Ticket Submission");

            // Ticket ID is generated by the DB. Can change to using UUID
            //ticket.ticket_id = Guid.NewGuid().ToString();

            ticket.status = TicketStatus.Open;
            ticket.time_stamp = DateTime.UtcNow;

            server.SupportTickets.Add(ticket);
            await server.SaveChangesAsync();

            return Ok( new { ticketId = ticket.ticket_id });
        }

        private void SendEmailConfirmation(SupportTicket ticket)
        {

        }
    }

}