using System;
using System.Net.Sockets;
using System.Net.WebSockets;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace wiFind.Server.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SupportTicketController : ControllerBase
    {
        private readonly WiFindContext _wifFindContext;

        public SupportTicketController(WiFindContext wifFindContext)
        {
            _wifFindContext = wifFindContext;
        }

        // Gets all tickets, only used by admins
        // TODO: Admin token validation
        [HttpGet("alltickets")]
        public async Task<IActionResult> GetTickets()
        {
            var ticketList = await _wifFindContext.SupportTickets.ToListAsync();
            return Ok(ticketList);
        }

        // TODO: Add Client token verification
        [HttpPost("submitticket")]
        public async Task<IActionResult> SubmitTicket(SupportTicket ticket)
        {
            if (!ModelState.IsValid) return BadRequest("Invalid Ticket Submission");

            // Ticket ID is generated by the DB. Can change to using UUID
            ticket.ticket_id = Guid.NewGuid().ToString();
            ticket.status = TicketStatus.Open;
            ticket.time_stamp = DateTime.UtcNow;

            _wifFindContext.SupportTickets.Add(ticket);
            await _wifFindContext.SaveChangesAsync();

            return Ok( new { ticketId = ticket.ticket_id });
        }

        // Removes tickets, only used by admins
        // TODO: admin token validation
        // Possibly add check for 'Complete' Status?
        [HttpDelete("removeicket")]
        public async Task<IActionResult> RemoveTicket(SupportTicket ticket)
        {
            var query = from t in _wifFindContext.Set<SupportTicket>() where t.ticket_id == ticket.ticket_id select t;
            _wifFindContext.Remove(query);
            await _wifFindContext.SaveChangesAsync();

            return Ok("Ticket removed");
        }

        // Sends user email of ticket submission receipt
        private void SendEmailConfirmation(SupportTicket ticket)
        {
            // Join ticket with accountInfo to get email.
            var query = from acctLogin in _wifFindContext.Set<AccountInfo>() join suppTicket in _wifFindContext.Set<SupportTicket>() on acctLogin.username equals ticket.username select acctLogin;
            var email = query.GetEnumerator().Current;

            // TODO: Rest of email logic
        }
    }

}